# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField()),
                ('album_p', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('contacto', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=250)),
                ('observaciones', models.CharField(max_length=250)),
            ],
        ),
    ]
