# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundacion', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
